- name: Demo on Loops
  hosts: localhost
  connection: local
  tasks:
    - name: Demo task for loop
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}, Quantity
      loop:
       - {name: apple, quantity: 10}
       - {name: banana, quantity: 20}